### PR TITLE
Removed lots of css not related to transitions directly

### PR DESCRIPTION
**Pull request by taromero**
This turned back my materializecss layout as it was before adding this package.

Did I delete too much?

I tested the few transitions I have on my app with this and they worked.

Addresses #3.

### CODE REVIEW

**Comment by yacinemerzouk** [comment]
Does this turn velociratchet into a generic native-feeling transition package, without any of the ratchet styles?

**Comment by taromero** [comment]
I ignored what Ratchet was, but basically yes, this prevents additional styles.

As the package author it's your call, but maybe allowing the user to add the styles on a separate package would be the best option. I tried to find a good transition library that plays well with Iron Router and this was the only one that worked well for me, but the additional styles broke the design of my app.

**Comment by yacinemerzouk** [comment]
I think we should keep velociratchet as is: a RatchetUI-based package. I'll create a new package that is mobile-framework agnostic. Give me 24-48 hours.

**Comment by taromero** [comment]
Great thanks!

**Comment by yacinemerzouk** [comment]
I removed all the RatchetUI-specific elements and I created a new repo:
https://github.com/zendylabs/segue-meteor-package

**Pull request closed without merging**
